heat_template_version: 2013-05-23

description: Image Factory

parameters:
  keypair_name:
    default: boat-comp
    description: Keypair to inject in instances
    type: string

  git_ansible_url:
    type: string
    label: Git repository of Ansible Playbook URL

  ansible_playbook:
    type: string
    label: target playbook path relative to git repository


resources:
  dmz:
    type: OS::Neutron::Net

  dmz_subnet:
    type: OS::Neutron::Subnet
    properties:
      network_id: { get_resource: dmz }
      ip_version: 4
      cidr: 10.42.42.0/24
      allocation_pools:
        - { start: 10.42.42.100, end: 10.42.42.199 }

  sg:
    type: OS::Neutron::SecurityGroup
    properties:
      rules:
        - { direction: ingress, protocol: TCP, port_range_min: 22, port_range_max: 22 }
        - { direction: ingress, protocol: TCP, port_range_min: 80, port_range_max: 80 }
        - { direction: egress, protocol: ICMP }
        - { direction: egress, protocol: TCP }
        - { direction: egress, protocol: UDP }

  ip:
    type: OS::Neutron::FloatingIP
    properties:
      floating_network_id: 6ea98324-0f14-49f6-97c0-885d1b8dc517

  server:
    type: OS::Nova::Server
    properties:
      key_name: { get_param: keypair_name }
      image: 9d9140a8-9dbf-4027-89b2-59205b02d383
      flavor: n1.cw.standard-2
      networks:
        - { network: { get_resource: dmz } }
      security_groups:
        - { get_resource: sg }
      user_data_format: RAW
      user_data:
        str_replace:
          template: |
            #!/bin/bash
            apt-get update
            apt-get upgrade -y
            apt-get install aptitude git python-dev python-pip curl -y
            pip install ansible
            mkdir /etc/ansible
            echo "[local]" > /etc/ansible/hosts
            echo "127.0.0.1 ansible_connection=local" >> /etc/ansible/hosts
            cd /root && git clone $git_ansible_url bootstrap
            /usr/local/bin/ansible-playbook /root/bootstrap/$ansible_playbook -vvv > /root/bootstrap.playbook.log 2>&1
          params:
            $git_ansible_url: { get_param: git_ansible_url }
            $ansible_playbook: { get_param: ansible_playbook }

  factory_internet_surface:
    type: OS::Nova::FloatingIPAssociation
    properties:
      floating_ip: { get_resource: ip }
      server_id: { get_resource: server }
