---
- name: packages installed
  apt:
    pkg="{{ item }}"
    state=present
  with_items:
    - openjdk-7-jre-headless
    - tomcat7

- name: tomcat running
  service:
    name=tomcat7
    state=running
    enabled=yes
